### ISSUE TITLE
Issue in creating /home directory

### ISSUE THREAD

**Issue by nagarajmmu** [HDFGroup/h5pyd#122] opened 2022-07-28 23:11 UTC
Hi 
 
I have installed HSDS in Azure cloud VM with ubuntu OS, installation is successful, but when I am doing, **Post Install Configuration**, I got an issue at creating "/home" folder, please find the error below.
I have used "_hstouch -u admin -p admin /home/_" command  to create "/home" folder.
ERROR:
**Unexpected error: HTTPConnectionPool(host='<VN_IP>', port=5101): Max retries exceeded with url: /?getdnids=1&getobjs=T&include_attrs=T&domain=%2Fhome (Caused by ResponseError('too many 500 error responses',))**

Please help me, if any configuration is missing. 
I am planning to create HDF5 file in Azure blob storage. Do I need to have "/home" folder for creating HDF5 file in Azure blob storage.

Please help me.

Thanks you

**Comment by jreadey** [comment] 2022-07-29 16:27
Hi - I suspect it's some configuration issue.    Does hsinfo run ok?  In general, if you are seeing 500 errors, you can do a "docker logs hsds_sn_1" and scan the output for lines with ERROR.  If the cause of the ERROR line is not obvious, please update this issue with the text.

BTW, you might be interested in the Azure Marketplace offer for HSDS: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/thehdfgroup1616725197741.hsdsazurevm.  This makes setup a little easier as it includes a VM image with the necessary packages and walks you through configuration steps.

**Comment by nagarajmmu** [comment] 2022-07-29 17:53
Hi Jreadey

Thanks for the update.
Yes "hsinfo" is working fine, below is the hsinfo response:
**server name**: Highly Scalable Data Service (HSDS)
**server state**: READY
**endpoint**: http://<Public_IP>:5101
**username**: admin (admin)
**password**: *****
**home**: NO ACCESS
**server version**: 0.7.0beta
**node count**: 4
**up**: 38 sec
**h5pyd version**: 0.10.1

Also I have verified the Docker logs, attached below.
ERROR: {"log":"ERROR\u003e request to http://<Private_IP>:6101/domains failed with code: 500\n","stream":"stdout","time":"2022-07-29T17:45:33.172949201Z"}

Above error is occurred 5 time.

Please let me know, if any configuration file you need for analysis. 

Thanks
Nagaraja M M

**Comment by nagarajmmu** [comment] 2022-07-29 21:09
Hi Jreadey

I have installed VM from Azure market place and setup hsds service, here also same issue, not able to create "/home" folder.
Response from "hsinfo" atatched below:
server name: Highly Scalable Data Service (HSDS)
server state: READY
endpoint: http://<IP>:5101
username: admin (admin)
password: *****
Error: HTTPConnectionPool(host='<IP>', port=5101): Max retries exceeded with url: /?domain=%2Fhome (Caused by ResponseError('too many 500 error responses',)

Please let me know, if any thing I am missing in setup, I am trying to create HDF5 file in azure blob.

Thanks
Nagaraja M M

**Comment by nagarajmmu** [comment] 2022-07-30 03:27
Hi John

Thanks for the analysis, yes, issue is authentication error. but not able to read error message in Azure log insights, but "AuthorizationError" count was increasing. 

I have given details in environment variables in .bashrc file as below
export BUCKET_NAME=<container_name>
export HSDS_ENDPOINT="http://<VM_IP>:5101"
export AZURE_CONNECTION_STRING="DefaultEndpointsProtocol=https;AccountName=<HOST_NAME>;AccountKey=<KEY>;EndpointSuffix=core.windows.net"

but not able to proceed, is above environment variables are fine?
Please let me know, if any think I need to do to fix this issue.

Thanks
Nagaraja M M

**Comment by jreadey** [comment] 2022-07-30 15:38
Are you seeing DN log authorization errors when trying to read/write to the blob storage?  You'll see errors in the logs with "azureBlobClient" that may provide more insight.  If you can copy and paste the relevant log error here that would be helpful.

**Comment by nagarajmmu** [comment] 2022-08-01 19:36
Hi John 

I am trying to read error logs in Azure blob, due to some issue, not able to read exact error log text in Azure.
But I have report generated by blob.
![image](https://user-images.githubusercontent.com/61146310/182229921-3fb82d91-a575-4291-84a1-fb0316eeb93c.png)

By above image I am able to understand that, "**ListBlobs**" and "**GetBlobProperties**" blob API's are failed, 

docker logs error attached below.
{"log":"REQ\u003e GET: / [/home]\n","stream":"stdout","time":"2022-08-01T18:23:55.651829661Z"}
{"log":"INFO\u003e got domain: hsdsblob/home\n","stream":"stdout","time":"2022-08-01T18:23:55.651863261Z"}
{"log":"INFO\u003e getDomainJson(hsdsblob/home, reload=True)\n","stream":"stdout","time":"2022-08-01T18:23:55.651868861Z"}
{"log":"INFO\u003e http_get('http://<IP_1>:6101/domains')\n","stream":"stdout","time":"2022-08-01T18:23:55.651873362Z"}
{"log":"INFO\u003e http_get status: 500 for req: http://<IP_1>:6101/domains\n","stream":"stdout","time":"2022-08-01T18:23:55.654286015Z"}
{"log":"ERROR\u003e request to http://<IP_1>:6101/domains failed with code: 500\n","stream":"stdout","time":"2022-08-01T18:23:55.654298415Z"}
{"log":"REQ\u003e GET: / [/home]\n","stream":"stdout","time":"2022-08-01T18:23:55.655834149Z"}
{"log":"INFO\u003e got domain: hsdsblob/home\n","stream":"stdout","time":"2022-08-01T18:23:55.655987053Z"}
{"log":"INFO\u003e getDomainJson(hsdsblob/home, reload=True)\n","stream":"stdout","time":"2022-08-01T18:23:55.655998153Z"}
{"log":"INFO\u003e http_get('http://<IP_1>:6101/domains')\n","stream":"stdout","time":"2022-08-01T18:23:55.656116856Z"}
{"log":"INFO\u003e http_get status: 500 for req: http://<IP_1>:6101/domains\n","stream":"stdout","time":"2022-08-01T18:23:55.658267003Z"}
{"log":"ERROR\u003e request to http://<IP_1>:6101/domains failed with code: 500\n","stream":"stdout","time":"2022-08-01T18:23:55.658279604Z"}
{"log":"REQ\u003e GET: / [/home]\n","stream":"stdout","time":"2022-08-01T18:23:57.662263968Z"}
{"log":"INFO\u003e got domain: hsdsblob/home\n","stream":"stdout","time":"2022-08-01T18:23:57.66236437Z"}
{"log":"INFO\u003e getDomainJson(hsdsblob/home, reload=True)\n","stream":"stdout","time":"2022-08-01T18:23:57.66237387Z"}
{"log":"INFO\u003e http_get('http://<IP_1>:6101/domains')\n","stream":"stdout","time":"2022-08-01T18:23:57.662421471Z"}
{"log":"INFO\u003e http_get status: 500 for req: http://<IP_1>:6101/domains\n","stream":"stdout","time":"2022-08-01T18:23:57.66552394Z"}
{"log":"ERROR\u003e request to http://<IP_1>:6101/domains failed with code: 500\n","stream":"stdout","time":"2022-08-01T18:23:57.665553241Z"}
{"log":"REQ\u003e GET: / [/home]\n","stream":"stdout","time":"2022-08-01T18:24:01.671964628Z"}
{"log":"INFO\u003e got domain: hsdsblob/home\n","stream":"stdout","time":"2022-08-01T18:24:01.672156533Z"}
{"log":"INFO\u003e getDomainJson(hsdsblob/home, reload=True)\n","stream":"stdout","time":"2022-08-01T18:24:01.672219134Z"}
{"log":"INFO\u003e http_get('http://<IP_1>:6101/domains')\n","stream":"stdout","time":"2022-08-01T18:24:01.672252635Z"}
{"log":"INFO\u003e http_get status: 500 for req: http://<IP_1>:6101/domains\n","stream":"stdout","time":"2022-08-01T18:24:01.675458806Z"}
{"log":"ERROR\u003e request to http://<IP_1>:6101/domains failed with code: 500\n","stream":"stdout","time":"2022-08-01T18:24:01.675502007Z"}
{"log":"INFO\u003e healthCheck - node_state: READY\n","stream":"stdout","time":"2022-08-01T18:24:04.119913135Z"}
{"log":"INFO\u003e register: http://head:5100/register\n","stream":"stdout","time":"2022-08-01T18:24:04.119945836Z"}
{"log":"INFO\u003e register req: http://head:5100/register body: {'id': 'sn-cb6c319d9372-dabe8', 'port': 5101, 'node_type': 'sn'}\n","stream":"stdout","time":"2022-08-01T18:24:04.119951336Z"}

Please let me know, if you are able to figure out the issue by above logs and image.

Thanks
Nagaraja M M

**Comment by jreadey** [comment] 2022-08-01 23:06
This looks strange - not sure why you are seeing the logs as json.
Did you do: ```docker logs hsds_sn_1```?  
Anyway, looks like it is the dn_1 container (i.e. the one running on port 6101) that is having the problems.
So try:   ```docker logs hsds_dn_1```.  If you see an error there it's likely it will have some information that will tell us what the problem is.

**Comment by jreadey** [comment] 2022-08-02 16:19
Ah, the problem is here: "Unable to import AzureBlobClient".

Looks like there was a change recently where the "azure-storage-blob" package was made optional in the setup script.  Fine for AWS, but no so good for Azure!

Let me confirm this and put out a new build for you to try.  Should have it sometime tomorrow.

**Comment by nagarajmmu** [comment] 2022-08-02 17:26
Hi John

Thank you for the update
Let me know, once new build is available, I will apply new build.

Thanks
Nagaraja M M

**Comment by jreadey** [comment] 2022-08-03 18:50
Hey,

   I have a fix checked into master now.  You can either build the image locally or use this DockerHub tag: hdfgroup/hsds:sha-164ea71.

   I tested it out on Azure and it looked like it worked ok - let me know if it works for you as well.

**Comment by nagarajmmu** [comment] 2022-08-03 23:39
Hi John

Thanks for the new build, it worked like a charm, now I am able to create hdf5 file in Azure blob.

Thanks a lot.

**Comment by jreadey** [comment] 2022-08-04 03:43
Awesome - I'll close this issue now.

**Closed by jreadey** 2022-08-04 03:43 UTC
